// this class returns a fake listing of the menu items

import 'package:charisma_of_india/customObjects/menu.dart';

class MenuListing {
  static List<Menu> getMenuItems() {
    return <Menu>[
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Char_Biryani.jpg',
        dishName: 'Charismatic Biryani',
        price: 22.99,
        dishDescription: 'Tender pieces of chicken, lamb, shrimp & vegetables cooked in Basmati Rice herbs & spices. A true delight!',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken-Biryani.jpg',
        dishName: 'Chicken Biryani',
        price: 17.59,
        dishDescription: 'Boneless pieces of baked tandoor chicken, blended with exotic spices',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Veg_Biryani.jpg',
        dishName: 'Vegetarian Biryani',
        price: 14.29,
        dishDescription: 'A blend of Basmati Rice and vegetables stir fried with several aromatic spices',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Veg_Biryani.jpg',
        dishName: 'Vegetarian Biryani',
        price: 14.29,
        dishDescription: 'A blend of Basmati Rice and vegetables stir fried with several aromatic spices',
        specialInstructions: 'lorem ipsum',
      ),Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Goat-Biryani.jpg',
        dishName: 'Goat Biryani',
        price: 18.69,
        dishDescription: 'Pieces of goat cooked with Basmati Rice and vegetables and spiced to your desire.',
        specialInstructions: 'lorem ipsum',
      ),Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Shrimp-Biryani.jpg',
        dishName: 'Shrimp Biryani',
        price: 18.69,
        dishDescription: 'Boneless chicken pieces cooked with Basmati Rice and vegetables with a blend of authentic herbs and spices.',
        specialInstructions: 'lorem ipsum',
      ),Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Vegetarian-Spring-Roll-Vegan.jpg',
        dishName: 'Vegetarian Spring Rolls',
        price: 2.99,
        dishDescription: 'Tasty paneer rolls packed with mixed vegetables and lightly deep fried .',
        specialInstructions: 'lorem ipsum',
      ),Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Vegtable-Pakora-Vegan.jpg',
        dishName: 'Vegetable Pakoras',
        price: 2.99,
        dishDescription: 'Spiced cauliflower, onion, potatoes battered in chickpea flour and deep fried in canola oil.',
        specialInstructions: 'lorem ipsum',
      ),Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Samosa_2.jpg',
        dishName: 'Vegetarian Samosas',
        price: 2.99,
        dishDescription: 'Crispy turnovers, delicately spiced and filled with potatoes and green peas',
        specialInstructions: 'lorem ipsum',
      ),Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Manchurian-Vegan.jpg',
        dishName: 'Vegetarian Manchurian (10 pcs)',
        price: 13.99,
        dishDescription: 'Finley chopped mixed vegetables sautéed with generous amounts garlic and ginger, Flavoured with soya sauce and vinegar',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Palak-Paneer.jpg',
        dishName: 'Palak Paneer',
        price: 15.99,
        dishDescription: 'Pureed spinach combined with paneer (homemade cheese) in a creamy sauce and 10 different spices. A Charisma favorite!',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chilli_Paneer.jpg',
        dishName: 'Chilli Paneer',
        price: 15.99,
        dishDescription: 'Paneer (Homemade cheese), fresh cut onions and bell peppers stir fried in a chilli sauce making this dish a spicy and falvourful innovation',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Malai_Kofta.jpg',
        dishName: 'Malai Kofta',
        price: 16.99,
        dishDescription: 'Vegetarian seasoned balls made from paneer (Home made cheese) potato, green peas , cooked in a creamy sauce',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Navratan_Korma.jpg',
        dishName: 'Navratan Korma/Vegetable Korma',
        price: 15.99,
        dishDescription: 'A royal entrée of mixed vegetables and paneer(homemade cheese) cooked in a creamy rich sauce with our special spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Aloo_Gobi.jpg',
        dishName: 'Aloo Gobi',
        price: 14.99,
        dishDescription: 'Potatoes and cauliflower sautéed with fresh ginger, garlic, onions and a blend of authentic herbs and spices',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Shahi_Paneer.jpg',
        dishName: 'Shahi Paneer',
        price: 16.99,
        dishDescription: 'Paneer (homemade cheese) immersed in a rich creamy sauce along with fresh ginger, garlic, onions and a blend of aromatic spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Dal_Makhni.jpg',
        dishName: 'Dal Makhani',
        price: 14.99,
        dishDescription: 'A blend of black beans and kidney beans boiled in a creamy sauce with exotic spices. This lentil curry is a delight for all!',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Muttar_Paneer.jpg',
        dishName: 'Muttar Paneer',
        price: 15.99,
        dishDescription: 'Green Peas mixed together with paneer in a rich creamy sauce with several Indian spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: '',
        dishName: '',
        price: 13.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Onion_Bhaji.jpg',
        dishName: 'Onion Bhaji',
        price: 14.99,
        dishDescription: 'Crispy onion fritters dipped in spiced gram flour batter, golden brown',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Dal_Tadka.jpg',
        dishName: 'Dal Tadka (Mixed Yellow lentils)',
        price: 14.99,
        dishDescription: 'Lentils tempered with onions, ginger, garlic, green chilli, cumin seeds and in a curry sauce',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Bhindi_Masala.jpg',
        dishName: 'Bhindi Masala',
        price: 15.99,
        dishDescription: 'Okra sautéed with onions and tomatoes mixed with aromatic, tangy spices',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Fish_Curry.jpg',
        dishName: 'Fish Curry',
        price: 16.99,
        dishDescription: 'Basa fish cooked in Ginger, garlic ,onions, tomatoes and savoury Indian spices.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Butter_Chicken.jpg',
        dishName: 'Butter Chicken',
        price: 17.99,
        dishDescription: 'Boneless pieces of baked tandoor chicken immersed in a heavenly tomato cream sauce and blended with exotic spices.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Goat_Curry.jpg',
        dishName: 'Goat Curry',
        price: 17.99,
        dishDescription: 'Tender cooked goat with ginger, garlic onions, tomatoes and spices',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Kadai-Chicken.jpg',
        dishName: 'Kadai Chicken',
        price: 16.99,
        dishDescription: 'Boneless chicken pieces cooked with a spicy masala paste, onions and tomatoes',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Mango_Chicken.jpg',
        dishName: 'Mango Chicken',
        price: 15.99,
        dishDescription: 'Boneless chicken pieces floating inside mango paste and a blend of spices. A creamy delight!',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Tandoori_Chicken.jpg',
        dishName: 'Tandoori Chicken ( 5 Pieces)',
        price: 15.99,
        dishDescription: 'Chicken marinated in homemade yogurt sauce and spices and then baked in the Tandoor oven. Served with basmati rice',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Palak_Chicken.jpg',
        dishName: 'Palak Chicken',
        price: 15.99,
        dishDescription: 'Tender boneless chicken pieces blended with pureed spinach and herbs',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Vindaloo.jpg',
        dishName: 'Chicken Vindaloo (Very Spicy)',
        price: 16.50,
        dishDescription: 'Boneless Chicken pieces immersed in a curry sauce with green chillies added for extra flavour. For those that like it spicy!!',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Shrimp_Korma.jpg',
        dishName: 'Shrimp Korma',
        price: 17.60,
        dishDescription: 'Shrimp cooked in a rich creamy spiced sauce',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Chana_Masala.jpg',
        dishName: 'Chicken Chana Masala',
        price: 14.99,
        dishDescription: 'Tender boneless chicken pieces mixed with chickpeas, tomatoes, and spices. A great combination',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Shrimp_Vindaloo.jpg',
        dishName: 'Shrimp Vindaloo',
        price: 16.99,
        dishDescription: 'Shrimp pieces immersed in a curry sauce with green chilies added for extra flavour. For those that like it spicy!!!',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Curry.jpg',
        dishName: 'Chicken Curry',
        price: 15.99,
        dishDescription: 'Boneless Chicken pieces in a tomato based curry with garlic, ginger and spices',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Kadai_Shrimp.jpg',
        dishName: 'Kadai Shrimp',
        price: 16.99,
        dishDescription: 'Shrimp cooked in a traditional wok-like dish and sautéed with several herbs and spices.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Patato_Shrimp_Curry.jpg',
        dishName: 'Potato Shrimp Curry',
        price: 15.99,
        dishDescription: 'Shrimp and potatoes tossed in a rich tomato sauce curry that is seasoned with our house spices.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Palak_Goat.jpg',
        dishName: 'Palak Goat',
        price: 19.99,
        dishDescription: 'A tremendous and mouth-watering combination of spinach and goat meat. A special delicacy cooked in Indian Spices',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: '',
        dishName: '',
        price: 14.99,
        dishDescription: '',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Subz.jpg',
        dishName: 'Chicken Subzi',
        price: 15.99,
        dishDescription: 'Tender boneless chicken pieces cooked with a variety of mixed vegetables and spices',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chilli_Chiken.jpg',
        dishName: 'Chilli Chicken',
        price: 17.99,
        dishDescription: 'Boneless chicken pieces baked and then stir fried with fresh onions, garlic, ginger, green peppers, and red peppers. A variety of authentic spices added to this mixture completes this entrée',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Kadai_Goat.jpg',
        dishName: 'Kadai Goat',
        price: 19.99,
        dishDescription: 'Goat cooked in a traditional wok-like dish and sautéed with several herbs and spices. An amazing dish!',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Masala.jpg',
        dishName: 'Chicken Masala',
        price: 16.99,
        dishDescription: 'Boneless chicken pieces in a tomato spiced curry and an addition of fried eggs to top off the flavour.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Korma.jpg',
        dishName: 'Chicken Korma',
        price: 16.50,
        dishDescription: 'Boneless Chicken pieces cooked in a rich creamy spiced sauce.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicken_Spicy.jpg',
        dishName: 'Spicy Chicken',
        price: 15.40,
        dishDescription: 'Marinated chicken cooked in yogurt and a blend of ginger, garlic, tomato sauce and a variety of spices.',
        specialInstructions: 'lorem ipsum',
      ), Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Shrimp_Curry.jpg',
        dishName: 'Shrimp Curry',
        price: 16.99,
        dishDescription: 'Shrimp cooked in Ginger, garlic ,onions, tomatoes and savoury Indian spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Aloo-Gobhi-Vegan.jpg',
        dishName: 'Aloo Gobi (Vegan)',
        price: 14.99,
        dishDescription: 'Potatoes and cauliflower sautéed with fresh ginger, garlic, onions and a blend of authentic herbs and spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Aloo-Muttar-Vegan.jpg',
        dishName: 'Aloo Muttar (Vegan)',
        price: 14.99,
        dishDescription: 'Potatoes cooked with green peas in a spiced sauce.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Vegetarian-Spring-Roll-Vegan.jpg',
        dishName: 'Vegetarian Spring Rolls 2 (Vegan) 2|6|12',
        price: 12.00,
        dishDescription: 'Paneer (Homemade cheese), fresh cut onions and bell peppers stir fried in a chilli sauce making this dish a spicy and falvourful innovation.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Manchurian-Vegan.jpg',
        dishName: 'Manchurian (Vegan)',
        price: 13.00,
        dishDescription: 'Our twist to an Indian/ Chinese dish. Made with cauliflower and other vegetables formed into balls and served in a delicious sweet and sour sauce that has garlic, onions, ginger, soya and several spices. Great as an appetizer or even an entrée!',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Mixed-Vegetable-Jaipuri-Vegan.jpg',
        dishName: 'Mixed Vegetable Jaipuri (Vegan)',
        price: 14.99,
        dishDescription: 'Assortment of Vegetables stir fried with a blend of authentic spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Baingan-Bharta-Vegan.jpg',
        dishName: 'Baingan Bharta (Vegan)',
        price: 16.49,
        dishDescription: 'Roasted Eggplants cooked with onion ,fresh tomato and green peas.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Chicpea-Channa-Masala-Vegan.jpg',
        dishName: 'Chickpea/Channa Masala (Vegan)',
        price: 14.99,
        dishDescription: 'Chickpeas cooked with fresh tomatoes, ginger, garlic, garam masala, coriander powder, chilli pepper & exotic spices.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Vegetable-Noodles.jpg',
        dishName: 'Vegetable Noodles(Vegan)',
        price: 10.99,
        dishDescription: 'Vegetarian Noodles with mixed vegetables',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Vegtable-Pakora-Vegan.jpg',
        dishName: 'Vegetable Pakora 24 pcs.(Vegan)',
        price: 14.99,
        dishDescription: 'Spiced cauliflower, onions and potatoes battered in chickpea flour and deep fried in canola oil.',
        specialInstructions: 'lorem ipsum',
      ),
      Menu(
        networkImage: 'https://charismaofindia.ca/wp-content/uploads/2020/12/Cumin-Patatoes.jpg',
        dishName: 'Cumin Potatoes (Vegan)',
        price: 14.99,
        dishDescription: 'Potato cubes stir fried into sizzling cumin and fenugreek seeds with dashes of turmeric and chilli powder',
        specialInstructions: 'lorem ipsum',
      ),
    ];
  }
}